#!/usr/bin/env python
# generate s3api delete object batches
# https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html
import sys
import json
j = {"Objects": [{"Key": "test1.txt"}],"Quiet": False}


def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in xrange(0, len(l), n):
        yield l[i:i + n]


f = open(sys.argv[1], 'r').readlines()
for i, chunk in enumerate(chunks(f, 1000)):
    objects = []
    for line in chunk:
        objects.append({"Key": (line.rstrip().split(' ')[-1])})
    j["Objects"] = objects
    with open("batch{}.json".format(i), "w") as batch:
        batch.write(json.dumps(j))
